
package com.example.politipal.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF724D9A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDAB5FF)
val onPrimaryContainerLight = Color(0xFF46216C)
val secondaryLight = Color(0xFF685878)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF0DDFF)
val onSecondaryContainerLight = Color(0xFF524261)
val tertiaryLight = Color(0xFF924465)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFACCA)
val onTertiaryContainerLight = Color(0xFF5F1A3A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF7FF)
val onBackgroundLight = Color(0xFF1D1A20)
val surfaceLight = Color(0xFFFFF7FF)
val onSurfaceLight = Color(0xFF1D1A20)
val surfaceVariantLight = Color(0xFFEADFED)
val onSurfaceVariantLight = Color(0xFF4B444F)
val outlineLight = Color(0xFF7C7481)
val outlineVariantLight = Color(0xFFCDC3D1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF332F35)
val inverseOnSurfaceLight = Color(0xFFF6EEF6)
val inversePrimaryLight = Color(0xFFDCB8FF)
val surfaceDimLight = Color(0xFFDFD8DF)
val surfaceBrightLight = Color(0xFFFFF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F1F9)
val surfaceContainerLight = Color(0xFFF3EBF3)
val surfaceContainerHighLight = Color(0xFFEDE6ED)
val surfaceContainerHighestLight = Color(0xFFE8E0E8)
